# Netflix Recommendation System:

## In this notebook, I had created a Netflix Recommendation System Using Cosine Similarity. You can download the dataset from [here.](https://www.kaggle.com/datasets/shivamb/netflix-shows)

In [1]:
import pandas as pd
df = pd.read_csv("E:/Downloads/My Projects with datasets/Netflix Dataset/netflix_titles.csv")
df.head()

show_id     type                  title         director  \
0      s1    Movie   Dick Johnson Is Dead  Kirsten Johnson   
1      s2  TV Show          Blood & Water              NaN   
2      s3  TV Show              Ganglands  Julien Leclercq   
3      s4  TV Show  Jailbirds New Orleans              NaN   
4      s5  TV Show           Kota Factory              NaN   

                                                cast        country  \
0                                                NaN  United States   
1  Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...   South Africa   
2  Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...            NaN   
3                                                NaN            NaN   
4  Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...          India   

           date_added  release_year rating   duration  \
0  September 25, 2021          2020  PG-13     90 min   
1  September 24, 2021          2021  TV-MA  2 Seasons   
2  September 24, 2021          2021  TV-MA   1 Season   
3  September 24, 2021          2021  TV-MA   1 Season   
4  September 24, 2021          2021  TV-MA  2 Seasons   

                                           listed_in  \
0                                      Documentaries   
1    International TV Shows, TV Dramas, TV Mysteries   
2  Crime TV Shows, International TV Shows, TV Act...   
3                             Docuseries, Reality TV   
4  International TV Shows, Romantic TV Shows, TV ...   

                                         description  
0  As her father nears the end of his life, filmm...  
1  After crossing paths at a party, a Cape Town t...  
2  To protect his family from a powerful drug lor...  
3  Feuds, flirtations and toilet talk go down amo...  
4  In a city of coaching centers known to train I...

In [2]:
df1 = df.drop(["type","date_added","release_year","duration"],axis = 1)
df1.head()

show_id                  title         director  \
0      s1   Dick Johnson Is Dead  Kirsten Johnson   
1      s2          Blood & Water              NaN   
2      s3              Ganglands  Julien Leclercq   
3      s4  Jailbirds New Orleans              NaN   
4      s5           Kota Factory              NaN   

                                                cast        country rating  \
0                                                NaN  United States  PG-13   
1  Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...   South Africa  TV-MA   
2  Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...            NaN  TV-MA   
3                                                NaN            NaN  TV-MA   
4  Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...          India  TV-MA   

                                           listed_in  \
0                                      Documentaries   
1    International TV Shows, TV Dramas, TV Mysteries   
2  Crime TV Shows, International TV Shows, TV Act...   
3                             Docuseries, Reality TV   
4  International TV Shows, Romantic TV Shows, TV ...   

                                         description  
0  As her father nears the end of his life, filmm...  
1  After crossing paths at a party, a Cape Town t...  
2  To protect his family from a powerful drug lor...  
3  Feuds, flirtations and toilet talk go down amo...  
4  In a city of coaching centers known to train I...

In [3]:
df1.cast[1]

'Ama Qamata, Khosi Ngema, Gail Mabalane, Thabang Molaba, Dillon Windvogel, Natasha Thahane, Arno Greeff, Xolile Tshabalala, Getmore Sithole, Cindy Mahlangu, Ryle De Morny, Greteli Fincham, Sello Maake Ka-Ncube, Odwa Gwanya, Mekaila Mathys, Sandi Schultz, Duane Williams, Shamilla Miller, Patrick Mofokeng'

In [4]:
df1['cast'] = df1['cast'].fillna("")
df1.cast.isna().sum()

0

In [5]:
df1.isna().sum()

show_id           0
title             0
director       2634
cast              0
country         831
rating            4
listed_in         0
description       0
dtype: int64

In [6]:
df1.shape

(8807, 8)

In [7]:
df1 = df1.fillna("")
df1.isna().sum()

show_id        0
title          0
director       0
cast           0
country        0
rating         0
listed_in      0
description    0
dtype: int64

In [8]:
df1.head()

show_id                  title         director  \
0      s1   Dick Johnson Is Dead  Kirsten Johnson   
1      s2          Blood & Water                    
2      s3              Ganglands  Julien Leclercq   
3      s4  Jailbirds New Orleans                    
4      s5           Kota Factory                    

                                                cast        country rating  \
0                                                     United States  PG-13   
1  Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...   South Africa  TV-MA   
2  Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...                 TV-MA   
3                                                                    TV-MA   
4  Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...          India  TV-MA   

                                           listed_in  \
0                                      Documentaries   
1    International TV Shows, TV Dramas, TV Mysteries   
2  Crime TV Shows, International TV Shows, TV Act...   
3                             Docuseries, Reality TV   
4  International TV Shows, Romantic TV Shows, TV ...   

                                         description  
0  As her father nears the end of his life, filmm...  
1  After crossing paths at a party, a Cape Town t...  
2  To protect his family from a powerful drug lor...  
3  Feuds, flirtations and toilet talk go down amo...  
4  In a city of coaching centers known to train I...

In [9]:
df1['text'] = df1['director'] + " " + df1['cast']+". "+df1['country']+". "+df1['rating']+". "+df1['listed_in']+". "+df1['description']
df1.head()

show_id                  title         director  \
0      s1   Dick Johnson Is Dead  Kirsten Johnson   
1      s2          Blood & Water                    
2      s3              Ganglands  Julien Leclercq   
3      s4  Jailbirds New Orleans                    
4      s5           Kota Factory                    

                                                cast        country rating  \
0                                                     United States  PG-13   
1  Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...   South Africa  TV-MA   
2  Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...                 TV-MA   
3                                                                    TV-MA   
4  Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...          India  TV-MA   

                                           listed_in  \
0                                      Documentaries   
1    International TV Shows, TV Dramas, TV Mysteries   
2  Crime TV Shows, International TV Shows, TV Act...   
3                             Docuseries, Reality TV   
4  International TV Shows, Romantic TV Shows, TV ...   

                                         description  \
0  As her father nears the end of his life, filmm...   
1  After crossing paths at a party, a Cape Town t...   
2  To protect his family from a powerful drug lor...   
3  Feuds, flirtations and toilet talk go down amo...   
4  In a city of coaching centers known to train I...   

                                                text  
0  Kirsten Johnson . United States. PG-13. Docume...  
1   Ama Qamata, Khosi Ngema, Gail Mabalane, Thaba...  
2  Julien Leclercq Sami Bouajila, Tracy Gotoas, S...  
3   . . TV-MA. Docuseries, Reality TV. Feuds, fli...  
4   Mayur More, Jitendra Kumar, Ranjan Raj, Alam ...

In [10]:
df2 = df1[['show_id','title',"text"]]
df2.head()

show_id                  title  \
0      s1   Dick Johnson Is Dead   
1      s2          Blood & Water   
2      s3              Ganglands   
3      s4  Jailbirds New Orleans   
4      s5           Kota Factory   

                                                text  
0  Kirsten Johnson . United States. PG-13. Docume...  
1   Ama Qamata, Khosi Ngema, Gail Mabalane, Thaba...  
2  Julien Leclercq Sami Bouajila, Tracy Gotoas, S...  
3   . . TV-MA. Docuseries, Reality TV. Feuds, fli...  
4   Mayur More, Jitendra Kumar, Ranjan Raj, Alam ...

### Creating Word Vectors using Word2vec :

In [11]:
import gensim
from gensim.models import Word2Vec

In [13]:
df3 = df2.drop("show_id",axis = 1)
df3['pre'] = df3.text.apply(gensim.utils.simple_preprocess)
df3.head()

title                                               text  \
0   Dick Johnson Is Dead  Kirsten Johnson . United States. PG-13. Docume...   
1          Blood & Water   Ama Qamata, Khosi Ngema, Gail Mabalane, Thaba...   
2              Ganglands  Julien Leclercq Sami Bouajila, Tracy Gotoas, S...   
3  Jailbirds New Orleans   . . TV-MA. Docuseries, Reality TV. Feuds, fli...   
4           Kota Factory   Mayur More, Jitendra Kumar, Ranjan Raj, Alam ...   

                                                 pre  
0  [kirsten, johnson, united, states, pg, documen...  
1  [ama, qamata, khosi, ngema, gail, mabalane, th...  
2  [julien, leclercq, sami, bouajila, tracy, goto...  
3  [tv, ma, docuseries, reality, tv, feuds, flirt...  
4  [mayur, more, jitendra, kumar, ranjan, raj, al...

In [15]:
df3.text[0]

'Kirsten Johnson . United States. PG-13. Documentaries. As her father nears the end of his life, filmmaker Kirsten Johnson stages his death in inventive and comical ways to help them both face the inevitable.'

In [14]:
df3.pre[0]

['kirsten',
 'johnson',
 'united',
 'states',
 'pg',
 'documentaries',
 'as',
 'her',
 'father',
 'nears',
 'the',
 'end',
 'of',
 'his',
 'life',
 'filmmaker',
 'kirsten',
 'johnson',
 'stages',
 'his',
 'death',
 'in',
 'inventive',
 'and',
 'comical',
 'ways',
 'to',
 'help',
 'them',
 'both',
 'face',
 'the',
 'inevitable']

In [16]:
model = Word2Vec(
    window = 6,
    min_count= 5,
    workers = 4
)

In [17]:
model.build_vocab(df3.pre)

In [18]:
model.corpus_count

8807

In [19]:
model.train(df3.pre, total_examples=model.corpus_count, epochs = 50)

(14572338, 20673150)

In [21]:
import numpy as np

### *Function for creating word vectors*:

In [27]:
def word_to_vev(df,model):
    vec = [model.wv[word] for word in df if word in model.wv ]
    return np.mean(vec,axis = 0) if vec else np.zeros(model.vector_size)

In [28]:
df3['vectors'] = df3.pre.apply(lambda x: word_to_vev(x,model))
df3.head()

title                                               text  \
0   Dick Johnson Is Dead  Kirsten Johnson . United States. PG-13. Docume...   
1          Blood & Water   Ama Qamata, Khosi Ngema, Gail Mabalane, Thaba...   
2              Ganglands  Julien Leclercq Sami Bouajila, Tracy Gotoas, S...   
3  Jailbirds New Orleans   . . TV-MA. Docuseries, Reality TV. Feuds, fli...   
4           Kota Factory   Mayur More, Jitendra Kumar, Ranjan Raj, Alam ...   

                                                 pre  \
0  [kirsten, johnson, united, states, pg, documen...   
1  [ama, qamata, khosi, ngema, gail, mabalane, th...   
2  [julien, leclercq, sami, bouajila, tracy, goto...   
3  [tv, ma, docuseries, reality, tv, feuds, flirt...   
4  [mayur, more, jitendra, kumar, ranjan, raj, al...   

                                             vectors  
0  [-0.11230055, 0.40650758, -0.33097607, -1.5762...  
1  [0.35718685, 0.5170654, -0.58824915, -0.389788...  
2  [-0.29257604, 0.0019006396, -0.4927487, -0.596...  
3  [-0.014827518, 0.8608093, -0.44325358, -0.2874...  
4  [-0.50537944, 0.35977322, -0.9136439, -0.11863...

In [29]:
df3.vectors[0]

array([-0.11230055,  0.40650758, -0.33097607, -1.5762104 ,  0.8970274 ,
        1.1238428 , -0.23529656, -0.9149384 ,  0.8307684 ,  0.5836787 ,
       -0.27742657,  0.42005342,  0.17096531, -0.15025154, -0.67068964,
        0.45573416, -0.44610304,  1.2781888 , -0.16758502,  1.3035902 ,
        0.17687616, -0.75001496, -0.23401453, -0.18462914, -0.5424387 ,
        0.13150513,  1.0866696 , -0.91662747, -0.28813985, -0.37234402,
       -0.6200152 , -0.47989872, -0.37888414,  0.29201493,  0.5042113 ,
       -0.789216  ,  0.57927763,  1.0290595 ,  0.7160699 ,  0.6202502 ,
        0.9240765 ,  0.37649444,  0.04568987,  0.01868076, -0.7565444 ,
       -0.27278665,  0.97693485, -0.05749008, -0.08675465, -0.43411016,
       -0.21090151, -1.0318936 ,  0.88386804, -0.6962973 , -0.24615034,
        0.16530433,  0.45073682,  0.15723638, -0.41266286, -0.16178595,
        0.19942735,  0.24537876,  0.67287946,  0.10548273, -0.24674717,
       -1.0639845 , -0.8794299 , -0.44686002,  0.68535334, -0.60

In [31]:
df4 = df3.drop(["text","pre"],axis = 1)
df4.head()

title                                            vectors
0   Dick Johnson Is Dead  [-0.11230055, 0.40650758, -0.33097607, -1.5762...
1          Blood & Water  [0.35718685, 0.5170654, -0.58824915, -0.389788...
2              Ganglands  [-0.29257604, 0.0019006396, -0.4927487, -0.596...
3  Jailbirds New Orleans  [-0.014827518, 0.8608093, -0.44325358, -0.2874...
4           Kota Factory  [-0.50537944, 0.35977322, -0.9136439, -0.11863...

## Using Cosine Similarity to Recommend Series:

In [33]:
from sklearn.metrics.pairwise import cosine_similarity
sim = cosine_similarity(df3.vectors.tolist(),df3.vectors.tolist())

In [34]:
sim

array([[1.0000001 , 0.55135655, 0.6481762 , ..., 0.7009635 , 0.5154631 ,
        0.70142466],
       [0.55135655, 0.99999994, 0.72050184, ..., 0.51545745, 0.43679932,
        0.60865   ],
       [0.6481762 , 0.72050184, 1.0000001 , ..., 0.5285745 , 0.5057335 ,
        0.6804541 ],
       ...,
       [0.7009635 , 0.51545745, 0.5285745 , ..., 1.0000002 , 0.6996415 ,
        0.5297513 ],
       [0.5154631 , 0.43679932, 0.5057335 , ..., 0.6996415 , 0.99999994,
        0.43645346],
       [0.70142466, 0.60865   , 0.6804541 , ..., 0.5297513 , 0.43645346,
        0.9999998 ]], dtype=float32)

In [38]:
df3[df3.title == "Blood & Water"].index

Index([1], dtype='int64')

In [47]:
list(enumerate(sim[df3[df3.title == "Blood & Water"].index]))

[(0,
  array([0.55135655, 0.99999994, 0.72050184, ..., 0.51545745, 0.43679932,
         0.60865   ], dtype=float32))]

In [53]:
for i in sim[1:5]:
    print(i)

[0.55135655 0.99999994 0.72050184 ... 0.51545745 0.43679932 0.60865   ]
[0.6481762  0.72050184 1.0000001  ... 0.5285745  0.5057335  0.6804541 ]
[0.6907696  0.701985   0.7103765  ... 0.5347943  0.40951678 0.5560862 ]
[0.55082494 0.7347889  0.7271406  ... 0.45915443 0.4149417  0.80949426]


### ***Function to recommend series:***

In [73]:
def recommend_series(title, top_n):
    idx = df3[df3.title == title].index[0]
    sm = list(enumerate(sim[idx]))
    soretd_list = sorted(sm, key =lambda x: x[1], reverse=True)
    top_indices = [i[0] for i in soretd_list[1:top_n + 1]]
    return df3.title.iloc[top_indices]

In [78]:
title = "Love on the Spectrum"
recommend_series(title,7)

1383                         Blown Away
3286                    My Dear Warrior
6763                    Fit for Fashion
1442         Korean Pork Belly Rhapsody
2657                 Win the Wilderness
8199                       The Bachelor
3796    Hyper HardBoiled Gourmet Report
Name: title, dtype: object